### ISSUE TITLE
Update Exposure & User Base queries

### ISSUE THREAD

**Issue by josephd8** [IndexCoop/index-coop-analytics#43]
Now that we have the first iteration of Uniswap v3 added to our ETH2x-FLI supply and exposure queries (https://github.com/SetProtocol/index-coop-analytics/pull/41), we need to expand Uniswap v3 to all products and to the Coop-wide queries.

I believe this is an exhaustive list of queries that need updated (all in `kpis/index-coop-kpis-dash/`):

- [ ] btc2x-fli-address-exposure.sql
- [ ] btc2x-fli-supply-breakdown.sql
- [ ] dpi-address-exposure.sql
- [ ] dpi-supply-breakdown.sql
- [ ] mvi-address-exposure.sql
- [ ] mvi-supply-breakdown.sql

Once those are done, we can update the Coop queries easily:

- [ ] index-coop-address-exposure-all.sql
- [ ] index-coop-address-exposure.sql
- [ ] index-coop-exposure.sql
- [ ] index-coop-supply-breakdown.sql

**Comment by josephd8** [comment]
@deepsp94 are you good to focus your attention here now that the other uniswap v2/v3 work is wrapped up?

**Comment by deepsp94** [comment]
@josephd8 yes for sure. Just seeing this after sending the same message to you on discord lol.

**Comment by deepsp94** [comment]
Noting here that this on hold. Reason: revamp of address exposure calculations (this is bullish)

**Comment by josephd8** [comment]
UPDATE: this issue is now referencing an update to all exposure and user base queries now that we have re-vamped our uni v2, sushi, and uni v3 exposure queries. 

note: also working on incorporating either user generated views or scheduled materialized views into this update to reduce the amount of code that is duplicated across the repo
