### ISSUE TITLE
TWG - Low Priority - High Effort - Live Financial Statement

### ISSUE THREAD

**Issue by jackiep00** [IndexCoop/index-coop-analytics#50]
Elias Simos built a really cool Dune Dashboard for Nexus Mutual that the TWG really likes: https://duneanalytics.com/eliasimos/Nexus-Mutual-Financials

This provides a pretty good template for the way we might structure our financial statement. Previous attempts to do this ran into the problems of trying to shoehorn what an Excel financial statement needs or requires into what Dune can do, which quickly ran aground. But with this as the basic framework, we might be able to create something that's live, useful, but still quite different from what the TWG is doing with excel and whatnot.

**Comment by josephd8** [comment]
@jackiep00 moved this to "in progress"

**Comment by jackiep00** [comment]
@josephd8 can I get permissions to change labels & assignees? gonna move this out from "in progress" to "backlog" or something. also i got a bunch of other TWG related issues i'd like to tag

**Comment by josephd8** [comment]
@jackiep00 @anthonymbowman do y'all think we are good to close this out and let Anthony create more granular issues as they come about?

**Comment by anthonymbowman** [comment]
@josephd8 Yes, I think that should be good
