### ISSUE TITLE
DPI Wallet Profile Analysis

### ISSUE THREAD

**Issue by josephd8** [IndexCoop/index-coop-analytics#74]
The GWG is looking for AWG's help to gain insight into the profiles of our large DPI holder user base.

Details for this can be found here:
https://docs.google.com/document/d/1MBsXlitIfmBaDhL_oGmBNnoqe3X5A3iTItsSMUqCoHA/edit#

**Comment by josephd8** [comment]
@Lorengo can you comment here so I can assign you?

**Comment by Lorengo** [comment]
I'm working on it.

**Comment by josephd8** [comment]
https://dune.xyz/loren/Index-Coop-DPI-Wallet-Profile-Analysis

**Comment by josephd8** [comment]
Hey @Lorengo - going to move this to "In Review" for a couple days.

Looks like we have an open PR on this already ( #80 ) - can you make sure all of files are updated and added to that PR? And can we also move the location of this project in the repo to `growth/dpi-wallet-profile-analysis`?

Thanks for the great work on this!
