### ISSUE TITLE
BED Product Dashboard

### ISSUE THREAD

**Issue by josephd8** [IndexCoop/index-coop-analytics#83]
North Star, Core KPIs, User Analytics, Product Analytics for BED.

@mkc306 is taking this on as the first part of the analytics internship.

Largely replication of the DPI & MVI dashboards (also the BED KPIs in the KPIs dashboard:
https://dune.xyz/jdcook/DPI
https://dune.xyz/jdcook/MVI
https://dune.xyz/jdcook/Index-Coop

**Comment by mkc306** [comment]
Working on it
