### ISSUE TITLE
DPI in Money Markets

### ISSUE THREAD

**Issue by josephd8** [IndexCoop/index-coop-analytics#92]
We have built a couple queries to track DPI units and USD in Money Markets.

https://dune.xyz/queries/135660
https://dune.xyz/queries/135720

Right now this consists of the following markets:

aDPI: https://etherscan.io/address/0x6f634c6135d2ebd550000ac92f494f9cb8183dae (Aave V2)
crDPI: https://etherscan.io/address/0x2a537fa9ffaea8c1a41d3c2b68a9cb791529366d (Cream V1)
cyDPI: https://etherscan.io/address/0x7736ffb07104c0c400bb0cc9a7c228452a732992 (Cream V2 - IronBank)
fDPI-19: https://etherscan.io/address/0xf06f65a6b7d2c401fcb8b3273d036d21fe2a5963 (Rari Fuse Pool 19 - IndexCoop)

The next steps are to add:

- [ ] borrow amount
- [ ] % utilization
- [ ] historical rates

**Comment by ripples3** [comment]
Hi @josephd8,
I will grab this issue. Thanks.

**Comment by josephd8** [comment]
@ripples3 how is this coming along? any questions?

**Comment by ripples3** [comment]
Hey @josephd8, Looks like I cannot query borrow from the current data tables of Ironbank and Rari Capital. I submitted SC to Dune for decoding.
Historical rates are also tricky. I will review docs of these protocols to understand how they calculate interest rates.

**Comment by Sidheartx** [comment]
hey @ripples3 just dropping in a comment as I saw that you were struggling with interest rates on Rari. As far as I know, each fuse pool on Rari is a compound fork so most events they emit should be similar. You will need the 'ftoken' market token contract decoded on dune. That should give you TVL/interest earned by market. 
If it makes your life any easier, check my query for compound https://dune.xyz/queries/113788

**Comment by ripples3** [comment]
Thanks @Sidheartx!  I did not know that the table you used exists. This is helpful for checking Aave rates.
ftoken contact is using a proxy so I submitted that SC instead of ftoken SC for decoding. Please let me know if this is wrong or not.

Submitted this: 0x67e70eeb9dd170f7b4a9ef620720c9069d5e706c
ftoken contract is: 0xF06f65a6b7D2c401FcB8B3273d036D21Fe2a5963

**Comment by Sidheartx** [comment]
hey @ripples3 i just checked the ftoken contract logs for this pool and looks like that's where the events are -https://etherscan.io/tx/0x1d0ea73a7712ed4e6316624ed345cf9d5d68604fb485fba0b168dde1eb278d6f#eventlog
but you might wanna submit both and see which one has what you need.

**Comment by ripples3** [comment]
@Sidheartx I did. Great suggestion! Thanks.

**Comment by ripples3** [comment]
Hey @josephd8, just wanted to give you an update on this. I submitted the wrong Rari Capital SC for decoding. I requested another SC decoding about 2 days ago. Also, the formula for Borrow APY for  Cream Finance is complex. I used **InterestEarned/Borrow**  Borrow APY instead. What are your thoughts on this formula?

Here is the query that I made (without Rari)
https://dune.xyz/queries/137526
https://dune.xyz/queries/149636

**Comment by josephd8** [comment]
Hey @ripples3 - I am pretty new to cERC20 contracts as well. I looked into what @Sidheartx said in discord here: https://discord.com/channels/762061559744299010/872447012195426334/887042606159241226

I think the translation of that into your queries would be to do InterestEarned / Total TVL instead of InterestEarned / Borrow ?

But I think we want to be trying to find Supply APY (at least it is higher priority) instead of Borrow APY?

**Comment by ripples3** [comment]
@josephd8, That was I typo. I DMed @Sidheartx for clarification

InterestEarned / Total TVL = Supply APY
InterestEarned / TotalBorrow = Borrow APY
 
 What do you think of these charts below? 
 
 Supply and Borrow APY for DPI in Money Markets
 https://dune.xyz/queries/149195
 
 Borrowed DPI in Money Markets
 https://dune.xyz/queries/152539
 
 
 Should I PR it to this path? https://github.com/SetProtocol/index-coop-analytics/tree/main/product/dpi

**Comment by josephd8** [comment]
@ripples3 can you PR it to the following directory: `product/dpi/money-markets` ?

And then can you share back with David via discord to get his feedback? I will move this to "In Review" while we have BD review and get the PR sorted
