### ISSUE TITLE
Net Inflows Monitoring

### ISSUE THREAD

**Issue by josephd8** [IndexCoop/index-coop-analytics#94]
inspiration and requests coming from GWG: https://docs.google.com/presentation/d/13N00brc-SozhHna3bM4Unc8iFWO_ly3E0w8UqcpnN6Y/edit#slide=id.gee85a2cbeb_0_70

initial work done here: https://dune.xyz/queries/141222

working with Mr Madila in GWG to build out the rest

**Comment by anthonymbowman** [comment]
going to work on this

**Comment by anthonymbowman** [comment]
[Inflow by Week, Product](https://dune.xyz/queries/142311)

**Comment by anthonymbowman** [comment]
[Dune: Inflow by Week, Product](https://dune.xyz/queries/142365)

**Comment by anthonymbowman** [comment]
Cumulative Inflows vs. AUM - [DPI](https://dune.xyz/queries/142372) | [MVI](https://dune.xyz/queries/142379) | BED | ETH2X-FLI | BTC2X-FLI

**Comment by anthonymbowman** [comment]
[Dashboard - Index: Net Inflows Monitoring](https://dune.xyz/anthonybowman/Index:-Net-Inflows-Monitoring)

**Comment by josephd8** [comment]
@anthonymbowman can you update here with any new links / progress? Is there still open tasks you are working on for this issue?

**Comment by josephd8** [comment]
@anthonymbowman moving this to "In Review" while we get the PR sorted

**Comment by josephd8** [comment]
@anthonymbowman are all the queries in this dashboard (https://dune.xyz/anthonybowman/Index:-Net-Inflows-Monitoring) represented in this PR? Going to merge this if so!

**Comment by anthonymbowman** [comment]
@josephd8 I am still adding the last few in. Will be done today.

**Comment by anthonymbowman** [comment]
@josephd8 you are good to go. thanks!
