### ISSUE TITLE
DATA KPIs at launch

### ISSUE THREAD

**Issue by anthonymbowman** [IndexCoop/index-coop-analytics#95]

**Comment by josephd8** [comment]
Base KPIs dash is up: https://dune.xyz/jdcook/DATA

Plan is to keep them in this dash so we can monitor over the first day or two after launch, and then when we get more volume in the pool (and thus a steadier price feed) I will update the starting date to be the launch date (9/23) and get DATA added to the Index Coop KPIs dash

This dash will become the DATA product dash and we will add more to it over time
